shoppingmall/buy/urls.py
from django.urls import  path

from . import views

app_name = 'buy'

urlpatterns = [

    path('add/int:product_id>/', views.add_buy, name ="add_buy"),
    path('', views.buy_detail, name='buy_detail')

]

shoppingmall/pick/urls.py
from django.urls import path
from . import views

app_name = 'pick'

urlpatterns =[
    path('add/<int:product_id>/', views.add_pick, name='add_pick'),
    path('', views.pick_detail, name ='pick_detail')

]

shoppingmall/shoppingmall/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from user.views import index, logout, RegisterView, LoginView
from product.views import UpdateView, ProductView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('logout/', logout),
    path('', index),
    path('register/', RegisterView.as_view()),
    path('login/', LoginView.as_view()),
    path('update/', UpdateView.as_view()),
    path('list/', ProductView),
    path('pick/', include('pick.urls')),
    path('buy/', include('buy.urls'))
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

shoppingmall/product/models.py
from django.contrib.auth.models import User
from django.db import models
import uuid

# Create your models here.



class Product(models.Model):
    title = models.CharField(max_length=64, verbose_name ="상품명")
    price = models.IntegerField(verbose_name="가격")
    discount = models.IntegerField(verbose_name="할인")

    description = models.TextField(verbose_name="설명")


    created_at = models.DateTimeField('date published', auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted = models.CharField(max_length=128, default=False)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)

    def __str__(self):
        return self.title

    class Meta:
        db_table = "products"
        verbose_name="상품"

# 다수의 이미지 업로드
class Photo(models.Model):
    post = models.ForeignKey(Product, on_delete=models.CASCADE, null= True)
    image = models.ImageField(upload_to='images', blank=True)

shoppingmall/product/forms.py
from django import forms
from .models import Product

class RegisterForm(forms.Form):


    title = forms.CharField(
        error_messages={
            'required': '상품명을 입력해주세요.'
        }, label="상품명", max_length=64)

    price = forms.IntegerField(
        error_messages={
            'required': '가격을 입력해주세요.'
        }, label="가격")

    discount = forms.IntegerField(
        error_messages={
            'required': "할인율을 입력해주세요."
        }, label="할인율")

    description = forms.CharField(widget=forms.Textarea,
        error_messages={
            'required': "제품설명을 입력해주세요."
        }, label="설명")



    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')
        price = cleaned_data.get('price')
        discount = cleaned_data.get('discount')
        description = cleaned_data.get('description')
        if Product.objects.filter(title=title).exists():
            self.add_error('title', '이미 존재하는 상품 입니다.')

shoppingmall/product/views.py
from django.shortcuts import render, redirect
from django.views.generic import FormView
from .forms import RegisterForm
from .models import Product, Photo


# Create your views here.


class UpdateView(FormView):
    template_name = "product/update.html"
    form_class = RegisterForm
    success_url = '/'


    def form_valid(self, form):


        title = form.data.get('title')
        price = form.data.get('price')
        discount = form.data.get('discount')
        description = form.data.get('description')


        product = Product(
            title=title,
            price=price,
            discount=discount,
            description=description,

        )

        product.save()
        # photo_list = self.request.FILES.getlist('imgs')
        # for item in photo_list:
        #     photo = Photo(
        #         item
        #     )

        if(self.request.method == 'POST'):


            for img in self.request.FILES.getlist('imgs'):

                photo = Photo()
                photo.post = product
                photo.image = img

                photo = Photo(

                    image = photo.image,
                    post = photo.post
                )
                photo.save()


        # self.request.session['user'] = id
        return super().form_valid(form)
    # def PhotoUpload(request):
    #     if(request.method == 'POST'):
    #         post = Product()
    #
    #
    #         for img in request.FILES.getlist('imgs'):
    #             photo = Photo()
    #             photo.post = post
    #             photo.image = img
    #             photo.save()
    #         return redirect('/' +str(post.id))
    #     else:
    #         return render(request, 'product/update.html')


def ProductView(request):
    products = Product.objects.all()
    context = {'products' : products}

    return render(request, "product/list.html", context)

shoppingmall/product/templates/product/base.html
<!doctype html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    {% block header %}
    {% endblock %}
</head>

<body>
    <div class="container">
        {% block contents %}
        {% endblock %}
    </div>
</body>

</html>

shoppingmall/product/templates/product/list.html
{% extends "product/base.html" %}

{% block contents %}

                        <table class="table my_custom_table">

                                <tr>
                                    <div class="text-center">
                                    <th colspan="10">
                                        <h3>구매 가능 목록</h3>

                                    </div>
                                </tr>

                        </table>



<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <td>
{% for product in products %}
    <dir>

         <div class = "row mx-auto">
                    <div class="col-20 col-sm-20 col-md-20 col-lg-6 text-center">
                        <table class="table my_custom_table">
                            <thread class="my_custom_thread">
                                <tr>
                                    <th colspan="30">
                                         ITEM

                                    </th>

                                </tr>
                            </thread>
                        </table>

                    </div>

                </div>


          {% for photo in product.photo_set.all %}
            <img src="{{ photo.image.url}}" width="150"><br>
          {% endfor %}

        <strong> {{product.title}}</strong>
        <br>
        price : {{product.price}}원
        <br>
        description :{{product.description}}
        <br>
        <a class = "btn btn-secondary" href="{%url 'pick:add_pick' product.id %}"> Pick</a>
        <br>
        --------------------------------------------------
        <br>


    </dir>
{% endfor %}
        <dir>
        <button class="btn btn-secondary" onclick="location.href='/'">홈으로</button>
        </dir>

</div>

{% endblock %}

shoppingmall/product/templates/product/update.html
{% extends "product/base.html" %}
{% block contents %}
<div class="row mt-5">
    <div class="col-12 text-center">
        <h1>제품등록</h1>
    </div>
</div>
<div class="row mt-5">
    <div class="col-12 text-center">
        {{error}}
    </div>
</div>
<div class="row mt-5">
    <div class="col-12">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                <label for="{{field.id_for_label }}">{{field.label}}</label>
                <input type={{field.field.widget.input_type}} class="form-control" id="{{field.id_for_label}}" placeholder="{{field.label}}" name="{{field.name}}"/>

            </div>
            {% if field.errors %}
            <span style="color:red">{{field.errors}}</span>

            {% endif %}
            {% endfor %}

            <div><input type="file" name="imgs" multiple></div>

            <button type="submit" class="btn btn-secondary">제품등록</button>

        </form>
        <button class="btn btn-secondary" onclick="location.href='/'">취소</button>
    </div>
</div>
{% endblock %}